// The hooks are the policy, and their contract with a bridge is narrow: JSON in,
// a decision out, exit 0. These pin the decision boundaries, because a hook that
// fails open is indistinguishable from a hook that is not installed.
//
// Run with `node --test test/`.
import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import test from "node:test";
import { fileURLToPath } from "node:url";

const HOOKS = path.join(path.dirname(fileURLToPath(import.meta.url)), "..", "hooks");

// A personal root for a hook to read its policy from, seeded from the package.
function rootWith(policy) {
  const home = fs.mkdtempSync(path.join(os.tmpdir(), "doppler-hook-"));
  fs.mkdirSync(path.join(home, "hooks"), { recursive: true });
  fs.mkdirSync(path.join(home, "policy"), { recursive: true });
  for (const f of ["guard.mjs", "policy.mjs", "session-init.mjs", "block-co-authored-by.mjs", "block-claude-pr-footer.mjs", "source-guard.mjs"]) {
    fs.copyFileSync(path.join(HOOKS, f), path.join(home, "hooks", f));
  }
  for (const [name, body] of Object.entries(policy)) {
    fs.writeFileSync(path.join(home, "policy", name), body);
  }
  return home;
}

// Hooks that read policy do so relative to their own file, so a seeded personal
// root has to be the copy that runs — invoking the package copy would silently
// read the package's policy/ instead, which is the real bug this harness shape
// exists to catch.
function run(hook, payload, { env = {}, home } = {}) {
  const file = home ? path.join(home, "hooks", hook) : path.join(HOOKS, hook);
  const r = spawnSync("node", [file], {
    input: JSON.stringify(payload),
    encoding: "utf8",
    env: { ...process.env, ...env },
  });
  assert.equal(r.status, 0, `${hook} must exit 0 even on internal error`);
  const out = r.stdout.trim();
  return out ? JSON.parse(out) : null;
}

const bash = (command) => ({ session_id: "s", tool: "bash", args: { command } });

test("guard denies a tool redirect and teaches the alternative", () => {
  const d = run("guard.mjs", bash("cat foo.json"), { env: { DOPPLER_STATE_DIR: os.tmpdir() } });
  assert.equal(d.decision, "deny");
  assert.match(d.reason, /read\(\{filePath/);
});

test("guard asks on the judgment tier rather than denying", () => {
  const d = run("guard.mjs", bash("git push --force origin main"), { env: { DOPPLER_STATE_DIR: os.tmpdir() } });
  assert.equal(d.decision, "ask");
  assert.match(d.reason, /--force-with-lease/);
});

test("guard honours its own bypass marker", () => {
  const d = run("guard.mjs", bash("# bypass: I need shell semantics\ncat foo.json"), { env: { DOPPLER_STATE_DIR: os.tmpdir() } });
  assert.equal(d, null, "a bypassed command must produce no opinion");
});

test("guard honours the session-wide bypass", () => {
  const d = run("guard.mjs", bash("cat foo.json"), {
    env: { DOPPLER_STATE_DIR: os.tmpdir(), DOPPLER_BYPASS_GUARDS: "1" },
  });
  assert.equal(d, null);
});

test("guard ignores tools it has no opinion about", () => {
  assert.equal(run("guard.mjs", { session_id: "s", tool: "write", args: {} }, { env: { DOPPLER_STATE_DIR: os.tmpdir() } }), null);
});

test("the attribution blockers deny and have no bypass", () => {
  const d = run("block-co-authored-by.mjs", bash('git commit -m "x" -m "Co-Authored-By: A <a@b.c>"'));
  assert.equal(d.decision, "deny");
  // Unbypassable on purpose, so a marker must not clear it.
  const bypassed = run("block-co-authored-by.mjs", bash('# bypass: approved\ngit commit -m "x" -m "Co-Authored-By: A <a@b.c>"'));
  assert.equal(bypassed.decision, "deny");
});

test("the PR-footer blocker needs both a PR write and the footer URL", () => {
  // The URL is the signal, and the footer text is not: a PR body may legitimately
  // quote the URL, so the shlex split has to tell prose from an invocation.
  const d = run("block-claude-pr-footer.mjs", bash('gh pr create --body "Generated by https://claude.com/claude-code"'));
  assert.equal(d.decision, "deny");
  assert.equal(run("block-claude-pr-footer.mjs", bash("gh pr view 1")), null, "a read is not a write");
  assert.equal(run("block-claude-pr-footer.mjs", bash('echo "https://claude.com/claude-code"')), null, "no PR write, no deny");
  // Describing the command in prose must not read as three adjacent tokens.
  assert.equal(run("block-claude-pr-footer.mjs", bash('echo "run gh pr create with the footer https://claude.com/claude-code"')), null);
});

test("source-guard asks on an untrusted source and honours the bypass", () => {
  const home = rootWith({ "source-allowlist.json": JSON.stringify({ trusted: ["~/.doppler/"] }) });
  try {
    const env = { DOPPLER_STATE_DIR: path.join(home, "state") };
    const asked = run("source-guard.mjs", bash("opencode plugin add some-pkg"), { env });
    assert.equal(asked.decision, "ask", "an untrusted source must ask");
    // The bridge tells the model to re-run with this marker, so it has to work.
    const bypassed = run("source-guard.mjs", bash("# bypass: approved\nopencode plugin add some-pkg"), { env });
    assert.equal(bypassed, null, "the advertised bypass must actually clear the ask");
    const trusted = run("source-guard.mjs", bash("opencode plugin add ~/.doppler/opencode/doppler.js"), { env });
    assert.equal(trusted, null, "a trusted source must pass untouched");
    assert.equal(run("source-guard.mjs", bash("opencode plugin list"), { env }), null, "read-only verbs never gate");
  } finally {
    fs.rmSync(home, { recursive: true, force: true });
  }
});

test("source-guard matches a trusted source behind flags", () => {
  const home = rootWith({ "source-allowlist.json": JSON.stringify({ trusted: ["~/.doppler/"] }) });
  try {
    // The tilde is not at the start of the argument here, which is exactly the
    // case a startsWith-style expansion silently fails to match.
    const d = run("source-guard.mjs", bash("opencode plugin add --global ~/.doppler/opencode/doppler.js"), {
      env: { DOPPLER_STATE_DIR: path.join(home, "state") },
    });
    assert.equal(d, null);
  } finally {
    fs.rmSync(home, { recursive: true, force: true });
  }
});

test("source-guard fails open with no policy file", () => {
  const home = rootWith({});
  try {
    const d = run("source-guard.mjs", bash("opencode plugin add some-pkg"), {
      env: { DOPPLER_STATE_DIR: path.join(home, "state") },
    });
    assert.equal(d.decision, "ask", "a missing allowlist must ask, not allow");
  } finally {
    fs.rmSync(home, { recursive: true, force: true });
  }
});

test("a bridge can supply its own source verbs", () => {
  const home = rootWith({ "source-allowlist.json": JSON.stringify({ trusted: [] }) });
  try {
    const env = { DOPPLER_STATE_DIR: path.join(home, "state") };
    // Not an OpenCode verb, so the default set has no opinion.
    assert.equal(run("source-guard.mjs", { ...bash("other-harness plugin add x"), source_patterns: ["\\bother-harness\\s+plugin\\b"] }, { env }).decision, "ask");
    assert.equal(run("source-guard.mjs", { ...bash("opencode plugin add x"), source_patterns: ["\\bother-harness\\s+plugin\\b"] }, { env }), null);
  } finally {
    fs.rmSync(home, { recursive: true, force: true });
  }
});

test("policy compiles to the host's permission map, verbatim", () => {
  const home = rootWith({
    "allowlist.json": JSON.stringify({
      allow: [{ pattern: "*DOPPLER_BYPASS_GUARDS=1 grep*" }],
      ask: [{ pattern: "*git push*" }],
      tools: { allow: ["webfetch"] },
    }),
  });
  try {
    const out = run("policy.mjs", {}, { home });
    assert.deepEqual(out, {
      permission: {
        webfetch: "allow",
        bash: { "*git push*": "ask", "*DOPPLER_BYPASS_GUARDS=1 grep*": "allow" },
      },
    });
    // Ask is inserted before allow so an overlap surfaces the stricter rule.
  } finally {
    fs.rmSync(home, { recursive: true, force: true });
  }
});

test("policy emits nothing rather than failing open on a missing allowlist", () => {
  const home = rootWith({});
  try {
    assert.deepEqual(run("policy.mjs", {}, { home }), { permission: {} });
  } finally {
    fs.rmSync(home, { recursive: true, force: true });
  }
});

test("policy emits no catch-all, so unmatched commands keep the host default", () => {
  const home = rootWith({ "allowlist.json": JSON.stringify({ ask: [{ pattern: "*git push*" }] }) });
  try {
    assert.deepEqual(Object.keys(run("policy.mjs", {}, { home }).permission.bash), ["*git push*"]);
  } finally {
    fs.rmSync(home, { recursive: true, force: true });
  }
});

test("policy honours its kill switch", () => {
  const home = rootWith({ "allowlist.json": JSON.stringify({ ask: [{ pattern: "*git push*" }] }) });
  try {
    assert.deepEqual(run("policy.mjs", {}, { home, env: { DOPPLER_DISABLE_POLICY: "1" } }), { permission: {} });
  } finally {
    fs.rmSync(home, { recursive: true, force: true });
  }
});

test("session-init writes state under the personal root, not a harness's home", () => {
  const home = rootWith({});
  const state = path.join(home, "state");
  try {
    assert.equal(run("session-init.mjs", { session_id: "ses_1" }, { env: { DOPPLER_STATE_DIR: state } }), null);
    const written = JSON.parse(fs.readFileSync(path.join(state, "ses_1.json"), "utf8"));
    assert.equal(written.session_id, "ses_1");
    // Re-running must not reset the counters.
    run("guard.mjs", bash("grep x"), { env: { DOPPLER_STATE_DIR: state } });
    assert.equal(JSON.parse(fs.readFileSync(path.join(state, "ses_1.json"), "utf8")).session_id, "ses_1");
  } finally {
    fs.rmSync(home, { recursive: true, force: true });
  }
});

test("a malformed payload is a no-op, never a crash", () => {
  for (const hook of ["guard.mjs", "source-guard.mjs", "block-co-authored-by.mjs", "policy.mjs"]) {
    const r = spawnSync("node", [path.join(HOOKS, hook)], { input: "{not json", encoding: "utf8" });
    assert.equal(r.status, 0, `${hook} must exit 0 on a malformed payload`);
  }
});
